scrape_data:
  description: >-
    Scrape the main discussion topic and all the comments from this reddit post: https://www.reddit.com/r/OpenAI/comments/1h7fm9k/its_official_theres_a_200_chatgpt_pro/
  expected_output: >-
    One json
  agent: >-
    web_scraper
sentiment_analysis:
  description: >-
    Analyse the reddit comments and provide the sentiment analysis on the topic
  expected_output: >-
    Overall assessement of positive, neutral or negative sentiment on the the following perspectives with a short explanation: 1. Price: too expensive/resonable/good price for value 2. Functionality: does the new price model justify the advanced features? 3. Competitive sentiment: is the new price model competitive with other providers?
  agent: >-
    analyser
